### ISSUE TITLE
Error installing package <name> does not match expected SHA256 for all plugins

### ISSUE THREAD

**Issue by twist3dimages** [7dJx1qP/stash-plugins#1]
24-02-15 17:16:35
Info    
Finished installing packages
2024-02-15 17:16:35
Error   
Error installing package stashUserscriptLibrary7dJx1qP from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (21b02cb4276747766b1ec64d67a5962db81e645fe1341e54a69f4644abb4816c) does not match expected SHA256 (f5bb25543e68a96c3fcb6be8306e681a444d3685823c625ff8a50fa48fcffff1)
2024-02-15 17:16:35
Info    
Installing package stashUserscriptLibrary7dJx1qP
2024-02-15 17:16:11
Info    
Finished installing packages
2024-02-15 17:16:10
Error   
Error installing package stashUserscriptLibrary7dJx1qP from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (21b02cb4276747766b1ec64d67a5962db81e645fe1341e54a69f4644abb4816c) does not match expected SHA256 (f5bb25543e68a96c3fcb6be8306e681a444d3685823c625ff8a50fa48fcffff1)
2024-02-15 17:16:10
Info    
Installing package stashUserscriptLibrary7dJx1qP
2024-02-15 17:16:10
Info    
Installing package stashTagImageCropper
2024-02-15 17:16:10
Error   
Error installing package stashUserscriptLibrary7dJx1qP from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (21b02cb4276747766b1ec64d67a5962db81e645fe1341e54a69f4644abb4816c) does not match expected SHA256 (f5bb25543e68a96c3fcb6be8306e681a444d3685823c625ff8a50fa48fcffff1)
2024-02-15 17:16:10
Info    
Installing package stashUserscriptLibrary7dJx1qP
2024-02-15 17:16:10
Info    
Installing package stashStats
2024-02-15 17:16:10
Error   
Error installing package stashUserscriptLibrary7dJx1qP from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (21b02cb4276747766b1ec64d67a5962db81e645fe1341e54a69f4644abb4816c) does not match expected SHA256 (f5bb25543e68a96c3fcb6be8306e681a444d3685823c625ff8a50fa48fcffff1)
2024-02-15 17:16:10
Info    
Installing package stashUserscriptLibrary7dJx1qP
2024-02-15 17:16:10
Error   
Error installing package stashStashIDInput from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (da8daa30808b613bb327253275f33d2f272453c59ed6ca57ef14259a26f75ce2) does not match expected SHA256 (0dd4795d0a1bd2ee3b3866f33367c39e452bd9c22c85003172cc65193d6dc7f7)
2024-02-15 17:16:10
Info    
Installing package stashStashIDInput
2024-02-15 17:16:10
Error   
Error installing package stashUserscriptLibrary7dJx1qP from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (21b02cb4276747766b1ec64d67a5962db81e645fe1341e54a69f4644abb4816c) does not match expected SHA256 (f5bb25543e68a96c3fcb6be8306e681a444d3685823c625ff8a50fa48fcffff1)
2024-02-15 17:16:10
Info    
Installing package stashUserscriptLibrary7dJx1qP
2024-02-15 17:16:10
Error   
Error installing package stashStashIDIcon from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (d3378c90856a10f28dfbcef9da478c409953d15e2b8822996424cdb44e79c0a6) does not match expected SHA256 (b63a26ee80e7e7dbb2d0bdac8431200cfb400a1720560bbcd34ae3aafdd8c71b)
2024-02-15 17:16:10
Info    
Installing package stashStashIDIcon
2024-02-15 17:16:10
Error   
Error installing package stashUserscriptLibrary7dJx1qP from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (21b02cb4276747766b1ec64d67a5962db81e645fe1341e54a69f4644abb4816c) does not match expected SHA256 (f5bb25543e68a96c3fcb6be8306e681a444d3685823c625ff8a50fa48fcffff1)
2024-02-15 17:16:10
Info    
Installing package stashUserscriptLibrary7dJx1qP
2024-02-15 17:16:10
Error   
Error installing package stashSetStashboxFavoritePerformers from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (32585ed66fcdaf37de2925f081d61a2b44d2cfd0e127029d1c2f9ff9b046cebb) does not match expected SHA256 (10a491cf8919804c8632953d6586931971119c0e7ef6f2d009164dafbd3bf36c)
2024-02-15 17:16:10
Info    
Installing package stashSetStashboxFavoritePerformers
2024-02-15 17:16:10
Error   
Error installing package stashUserscriptLibrary7dJx1qP from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (21b02cb4276747766b1ec64d67a5962db81e645fe1341e54a69f4644abb4816c) does not match expected SHA256 (f5bb25543e68a96c3fcb6be8306e681a444d3685823c625ff8a50fa48fcffff1)
2024-02-15 17:16:10
Info    
Installing package stashUserscriptLibrary7dJx1qP
2024-02-15 17:16:10
Error   
Error installing package stashSceneTaggerDraftSubmit from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (90a22251d6d32e5ec0f708af456024941510f5332d078029726b7a51fd70602b) does not match expected SHA256 (9256095d4ae0df136622fa4ac2752c74bb527a2775828468f10321a3e5bdbc5e)
2024-02-15 17:16:10
Info    
Installing package stashSceneTaggerDraftSubmit
2024-02-15 17:16:10
Error   
Error installing package stashUserscriptLibrary7dJx1qP from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (21b02cb4276747766b1ec64d67a5962db81e645fe1341e54a69f4644abb4816c) does not match expected SHA256 (f5bb25543e68a96c3fcb6be8306e681a444d3685823c625ff8a50fa48fcffff1)
2024-02-15 17:16:10
Info    
Installing package stashUserscriptLibrary7dJx1qP
2024-02-15 17:16:10
Info    
Installing package stashSceneTaggerColorizer
2024-02-15 17:16:10
Error   
Error installing package stashUserscriptLibrary7dJx1qP from https://7djx1qp.github.io/stash-plugins/main/index.yml: installing package: package data (21b02cb4276747766b1ec64d67a5962db81e645fe1341e54a69f4644abb4816c) does not match expected SHA256 (f5bb25543e68a96c3fcb6be8306e681a444d3685823c625ff8a50fa48fcffff1)

**Comment by 7dJx1qP** [comment]
When did you add the https://7djx1qp.github.io/stash-plugins/main/index.yml source to your stash? Those expected hashes look like the old hashes before the update I made today.

I think stash is supposed to keep https://7djx1qp.github.io/stash-plugins/main/index.yml up to date and refresh it, but I'm not sure on the exact details. It might be fixed with clicking check for updates or restarting stash. I think removing the source and re-adding https://7djx1qp.github.io/stash-plugins/main/index.yml should definitely fix it. Github pages might have also been slow to update https://7djx1qp.github.io/stash-plugins/main/index.yml with the latest, because I know there's some caching done there.

**Comment by 7dJx1qP** [comment]
Actually, I think it's just github pages being slow to clear its cache and serve the latest build. I'm seeing that https://7djx1qp.github.io/stash-plugins/main/index.yml is still outdated despite the index.yml in the build artifact being correct.

**Comment by 7dJx1qP** [comment]
For some reason https://7djx1qp.github.io/stash-plugins/main/index.yml keeps reverting. I've redeployed to github pages twice and it will then show the updated version, but after a few minutes I see it reverting back after refreshing.
