### ISSUE TITLE
Studio page URL change on latest dev builds

### ISSUE THREAD

**Issue by floydcg** [7dJx1qP/stash-plugins#3]
The URL for studios has changed from http://<server>:9999/studios/###?c= to http://<server>:9999/studios/###/scenes?c= in the latest dev builds, which breaks user script functionality on the studio scraper pages. Prolly a simple fix

**Comment by floydcg** [comment]
I think based on some quick testing, line 587 of the userscriptlibrary needs to be updated to this: `                else if (this.matchUrl(location, /\/studios\/\d+\/scenes/)) {`

**Comment by 7dJx1qP** [comment]
This should be fixed in the latest version. Thanks for the report.
